# Generated by Django 5.0 on 2023-12-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_project_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partner_images/', verbose_name='Project Image (220*150)')),
            ],
            options={
                'verbose_name_plural': '06. Partners',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '06. Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects_images/', verbose_name='Project Image (1200*800)'),
        ),
    ]
