# Generated by Django 5.0 on 2023-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_partner_alter_project_options_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Project Image (1920*900)')),
            ],
            options={
                'verbose_name_plural': '06. Slider',
            },
        ),
    ]
